name: 12049Neuk√∂lln
favicon: null
layout_spectrum: 0.09569709771312773
typography_spectrum: 0.7349485165905207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5775384067092091
  lightness: 0.40891846269369125
  saturation: 0.08263783529400826
  rhythmicContrast: 0.9451840189285576
purpose: []
